# 58 wilayas of Algeria with their main communes (used to seed the delivery module).
# Format: (code, name, [main communes/cities])
WILAYAS_SEED = [
    ("01", "Adrar", ["Adrar", "Reggane", "Aoulef", "Zaouiet Kounta", "Fenoughil", "Tsabit"]),
    ("02", "Chlef", ["Chlef", "Ténès", "Ouled Farès", "Chettia", "Boukadir", "Oued Fodda"]),
    ("03", "Laghouat", ["Laghouat", "Aflou", "Ksar El Hirane", "Aïn Madhi", "Hassi R'Mel"]),
    ("04", "Oum El Bouaghi", ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Meskiana", "Aïn Fakroun"]),
    ("05", "Batna", ["Batna", "Barika", "Merouana", "Arris", "Aïn Touta", "Tazoult"]),
    ("06", "Béjaïa", ["Béjaïa", "Akbou", "Amizour", "El Kseur", "Kherrata", "Tichy"]),
    ("07", "Biskra", ["Biskra", "Tolga", "Sidi Okba", "Ouled Djellal", "El Kantara", "Zeribet El Oued"]),
    ("08", "Béchar", ["Béchar", "Kenadsa", "Abadla", "Beni Ounif", "Taghit"]),
    ("09", "Blida", ["Blida", "Boufarik", "Bouinan", "Larbaâ", "Mouzaïa", "Ouled Yaïch"]),
    ("10", "Bouira", ["Bouira", "Lakhdaria", "Sour El Ghozlane", "M'Chedallah", "Aïn Bessem"]),
    ("11", "Tamanrasset", ["Tamanrasset", "Abalessa", "In Amguel", "Idlès", "Tazrouk"]),
    ("12", "Tébessa", ["Tébessa", "Bir El Ater", "Cheria", "El Aouinet", "Morsott"]),
    ("13", "Tlemcen", ["Tlemcen", "Maghnia", "Ghazaouet", "Nedroma", "Remchi", "Sebdou"]),
    ("14", "Tiaret", ["Tiaret", "Sougueur", "Frenda", "Mahdia", "Ksar Chellala", "Aïn Deheb"]),
    ("15", "Tizi Ouzou", ["Tizi Ouzou", "Azazga", "Draâ El Mizan", "Larbaâ Nath Irathen", "Boghni", "Aïn El Hammam"]),
    ("16", "Alger", ["Alger-Centre", "Bab El Oued", "El Harrach", "Draria", "Rouiba", "Bir Mourad Raïs", "Hussein Dey", "Chéraga", "Dar El Beïda", "Baraki"]),
    ("17", "Djelfa", ["Djelfa", "Aïn Oussera", "Messaad", "Hassi Bahbah", "El Idrissia"]),
    ("18", "Jijel", ["Jijel", "Taher", "El Milia", "Chekfa", "El Aouana"]),
    ("19", "Sétif", ["Sétif", "El Eulma", "Aïn Oulmène", "Bougaâ", "Aïn Arnat", "Guenzet"]),
    ("20", "Saïda", ["Saïda", "Aïn El Hadjar", "Youb", "Sidi Boubekeur", "El Hassasna"]),
    ("21", "Skikda", ["Skikda", "Azzaba", "Collo", "El Harrouch", "Tamalous", "Ramdane Djamel"]),
    ("22", "Sidi Bel Abbès", ["Sidi Bel Abbès", "Telagh", "Sfisef", "Ben Badis", "Ras El Ma"]),
    ("23", "Annaba", ["Annaba", "El Bouni", "Berrahal", "El Hadjar", "Aïn Berda", "Seraïdi"]),
    ("24", "Guelma", ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis", "Khezara"]),
    ("25", "Constantine", ["Constantine", "El Khroub", "Aïn Smara", "Hamma Bouziane", "Didouche Mourad", "Zighoud Youcef"]),
    ("26", "Médéa", ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Beni Slimane", "Tablat"]),
    ("27", "Mostaganem", ["Mostaganem", "Sidi Ali", "Aïn Tédelès", "Bouguirat", "Hassi Mameche"]),
    ("28", "M'Sila", ["M'Sila", "Bou Saâda", "Sidi Aïssa", "Aïn El Melh", "Magra", "Hammam Dhalaâ"]),
    ("29", "Mascara", ["Mascara", "Sig", "Mohammadia", "Tighennif", "Bou Hanifia", "Ghriss"]),
    ("30", "Ouargla", ["Ouargla", "Hassi Messaoud", "Touggourt", "N'Goussa", "Rouissat"]),
    ("31", "Oran", ["Oran", "Es Sénia", "Bir El Djir", "Aïn El Turk", "Arzew", "Bethioua", "Gdyel"]),
    ("32", "El Bayadh", ["El Bayadh", "Rogassa", "Bougtoub", "El Abiodh Sidi Cheikh", "Brezina"]),
    ("33", "Illizi", ["Illizi", "Djanet", "In Amenas", "Debdeb"]),
    ("34", "Bordj Bou Arréridj", ["Bordj Bou Arréridj", "Ras El Oued", "Mansoura", "El Achir", "Medjana"]),
    ("35", "Boumerdès", ["Boumerdès", "Boudouaou", "Bordj Menaïel", "Dellys", "Thénia", "Khemis El Khechna"]),
    ("36", "El Tarf", ["El Tarf", "El Kala", "Ben M'Hidi", "Bouhadjar", "Dréan"]),
    ("37", "Tindouf", ["Tindouf", "Oum El Assel"]),
    ("38", "Tissemsilt", ["Tissemsilt", "Théniet El Had", "Bordj Bou Naama", "Lardjem", "Khemisti"]),
    ("39", "El Oued", ["El Oued", "Guemar", "Djamaa", "Robbah", "Debila", "Bayadha"]),
    ("40", "Khenchela", ["Khenchela", "Kaïs", "Chechar", "El Hamma", "Bouhmama"]),
    ("41", "Souk Ahras", ["Souk Ahras", "Sedrata", "M'Daourouch", "Taoura", "Bir Bou Haouch"]),
    ("42", "Tipaza", ["Tipaza", "Cherchell", "Hadjout", "Koléa", "Fouka", "Bou Ismaïl"]),
    ("43", "Mila", ["Mila", "Ferdjioua", "Chelghoum Laïd", "Grarem Gouga", "Tadjenanet"]),
    ("44", "Aïn Defla", ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf", "Djelida"]),
    ("45", "Naâma", ["Naâma", "Mécheria", "Aïn Sefra", "Sfissifa", "Tiout"]),
    ("46", "Aïn Témouchent", ["Aïn Témouchent", "Hammam Bou Hadjar", "Beni Saf", "El Malah", "Aghlal"]),
    ("47", "Ghardaïa", ["Ghardaïa", "Metlili", "El Guerrara", "Berriane", "Bounoura", "Daya Ben Dahoua"]),
    ("48", "Relizane", ["Relizane", "Oued Rhiou", "Mazouna", "Zemmoura", "Ammi Moussa"]),
    ("49", "Timimoun", ["Timimoun", "Ouled Saïd", "Aougrout", "Charouine", "Tinerkouk"]),
    ("50", "Bordj Badji Mokhtar", ["Bordj Badji Mokhtar", "Timiaouine"]),
    ("51", "Ouled Djellal", ["Ouled Djellal", "Sidi Khaled", "Doucen", "Ras El Miaad"]),
    ("52", "Béni Abbès", ["Béni Abbès", "Igli", "Kerzaz", "Ouled Khoudir", "Tabelbala"]),
    ("53", "In Salah", ["In Salah", "Foggaret Ezzoua", "In Ghar"]),
    ("54", "In Guezzam", ["In Guezzam", "Tin Zaouatine"]),
    ("55", "Touggourt", ["Touggourt", "Témacine", "Megarine", "El Hadjira", "Nezla"]),
    ("56", "Djanet", ["Djanet", "Bordj El Haouasse"]),
    ("57", "El M'Ghair", ["El M'Ghair", "Djamaa", "Sidi Amrane", "Still", "Oum Touyour"]),
    ("58", "El Meniaa", ["El Meniaa", "Hassi Gara", "Hassi Fehal"]),
]
